/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2023-04-12 01:27:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.JUS;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class TestComment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/JUS/work/DevfoxProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DevJUS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1672725238227L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("		<!-- Bootstrap ! -->\r\n");
      out.write("  		<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ\" crossorigin=\"anonymous\">\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/resources/css/styles.css\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	 <!-- Comments section-->\r\n");
      out.write("         <section class=\"mb-5\">\r\n");
      out.write("            <div class=\"card bg-light\">\r\n");
      out.write("               <div class=\"card-body\" >\r\n");
      out.write("				<input type=\"hidden\" name=\"board_idx\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_idx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"board_idx\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                     <textarea class=\"form-control\" rows=\"1\" id=\"reContent\"></textarea>\r\n");
      out.write("                          <div style=\"text-align: right;\">\r\n");
      out.write("                           <button type=\"button\" id=\"bsub\" style=\"padding: 15px; margin: 20px;\">등록</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                         <!-- Comment with nested comments-->\r\n");
      out.write("                            <div id=\"card-bodyo\">\r\n");
      out.write("                            \r\n");
      out.write("                            </div>    \r\n");
      out.write(" \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div id=\"oup2\">\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"position: relative; min-height: 100px; margin-top: 12px; border: 1px solid #b3b3b3; box-sizing: border-box;\">\r\n");
      out.write("					<nav aria-label=\"Page navigation example\">\r\n");
      out.write("						<ul class=\"pagination justify-content-center pagination-xl\">\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("						</ul>\r\n");
      out.write("					</nav>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("                    </section>\r\n");
      out.write(" <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write(" <script>\r\n");
      out.write(" $(document).ready(function() {\r\n");
      out.write("	 var TotList = []; // 댓글 리스트  배열\r\n");
      out.write("	 var pageCount = 0; // 총 페이지\r\n");
      out.write("	 var pagination = $(\"#oup2 .pagination\");// 버튼 추가 자리\r\n");
      out.write("	 $.ajax({\r\n");
      out.write("		 url: \"reTestCommentList\",\r\n");
      out.write("		 type: \"get\",\r\n");
      out.write("		 contentType: \"application/json; charset=UTF-8\",\r\n");
      out.write("		 dataType: \"json\",\r\n");
      out.write("		 success: function(data){\r\n");
      out.write("			 console.log(data.comment_idx);\r\n");
      out.write("			 \r\n");
      out.write("			 TotList = data;\r\n");
      out.write("			 Listsize = TotList.length;\r\n");
      out.write("			// 페이지 수 계산\r\n");
      out.write("	        pageCount = Math.ceil(Listsize / 10);\r\n");
      out.write("	        console.log(pageCount);\r\n");
      out.write("	     	// 페이지 버튼 생성 함수\r\n");
      out.write("            function createPageButton(pageNum) {\r\n");
      out.write("              var pageLink = $(\"<li class='page-link'></li>\").text(pageNum).attr('data-page', pageNum);\r\n");
      out.write("              var pageBtn = $(\"<li class='page-item'></li>\").append(pageLink);\r\n");
      out.write("              return pageBtn;\r\n");
      out.write("            }\r\n");
      out.write("         	// 페이지 버튼 보이기/숨기기 처리\r\n");
      out.write("            setPageButtonVisibility(1, pageCount);\r\n");
      out.write("	     	\r\n");
      out.write("	     	\r\n");
      out.write("            // 페이지 버튼 보이기/숨기기 처리 함수\r\n");
      out.write("	           function setPageButtonVisibility(start, end) {\r\n");
      out.write("	        	pagination.find('.page-item').remove();\r\n");
      out.write("				if (pageCount > 1) {\r\n");
      out.write("				    for (var i = start; i <= 10; i++) {\r\n");
      out.write("				      pagination.find('.page-item:nth-child(' + i + ')').show();\r\n");
      out.write("				    }\r\n");
      out.write("\r\n");
      out.write("					 }\r\n");
      out.write("				// 페이지 버튼 추가\r\n");
      out.write("     			if(pageCount > 1) {\r\n");
      out.write("     				pagination.empty();\r\n");
      out.write("     				//pagination.append(prevBtn);\r\n");
      out.write("	            	for (var i = 1; i <= 10  ; i++) {\r\n");
      out.write("	             	 pagination.append(createPageButton(i));\r\n");
      out.write("	             		//pagetotcount++;\r\n");
      out.write("	          		  }\r\n");
      out.write("	            	\r\n");
      out.write("	            	 pagination.append(nextBtn);\r\n");
      out.write("     			}else{\r\n");
      out.write("     				pagination.empty()\r\n");
      out.write("     				pagination.append(createPageButton(1));\r\n");
      out.write("     			}\r\n");
      out.write("     			\r\n");
      out.write("				}\r\n");
      out.write("	           RList(data)\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("	 	}\r\n");
      out.write(" 	})\r\n");
      out.write(" })\r\n");
      out.write(" //대댓글 버튼 누를시\r\n");
      out.write(" $(document).on(\"click\",'button[name=\"but\"]',function() {\r\n");
      out.write(" 	    // 대댓글 작성 버튼의 ID에서 댓글 번호 추출\r\n");
      out.write(" 	    var commentIdx = $(this).attr('id').split('-')[2];\r\n");
      out.write(" 	    var dvreCont = $('#dvreCont' + commentIdx);\r\n");
      out.write(" 	    \r\n");
      out.write(" 	    // 현재 요소의 display 속성 값을 체크하여 보이게 하거나 숨기기\r\n");
      out.write(" 	    if (dvreCont.css('display') === 'none') {\r\n");
      out.write(" 	    	dvreCont.show();\r\n");
      out.write(" 	    } else {\r\n");
      out.write(" 	    	dvreCont.hide();\r\n");
      out.write(" 	    }\r\n");
      out.write(" 	});\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" //댓글 insert\r\n");
      out.write(" $('#bsub').on(\"click\", function() {\r\n");
      out.write("	 var board_idx = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("	 var user_name = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("	 var comment_content = $(\"#reContent\").val();\r\n");
      out.write("	 console.log(board_idx);\r\n");
      out.write("	 console.log(comment_content);\r\n");
      out.write("	 console.log(user_name);\r\n");
      out.write("	 $.ajax({\r\n");
      out.write("		 url : \"reTestComment\",\r\n");
      out.write("		 data : {\r\n");
      out.write("			 board_idx : board_idx,\r\n");
      out.write("			 comment_content : comment_content,\r\n");
      out.write("			 user_name : user_name\r\n");
      out.write("		 },\r\n");
      out.write("		 type : \"Post\",\r\n");
      out.write("		 success : function(data){\r\n");
      out.write("			 console.log(\"성공\")\r\n");
      out.write("			 $('#reContent').val('') //댓글 등록시 댓글 등록창 초기화\r\n");
      out.write("				getReplyList(); //등록후 댓글 목록 불러오기 함수 실행\r\n");
      out.write("		 }\r\n");
      out.write("	 })\r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write(" //대댓글 등록\r\n");
      out.write(" $(document).on(\"click\",'button[name=\"bsub\"]',function(){\r\n");
      out.write("	// 대댓글 등록 버튼의 ID에서 댓글 번호 추출\r\n");
      out.write("	   var comment_idx = $(this).attr('id').split('-')[1];//부모 댓글 idx\r\n");
      out.write("	   var comment_nb = $(this).attr('id').split('-')[2];//대댓글 위사람\r\n");
      out.write("	   var board_idx = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"// 글 idx\r\n");
      out.write("	   var user_name = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" // 댓글 작성유저\r\n");
      out.write("	   var comment_content = $(\"#reContent\"+comment_nb).val();\r\n");
      out.write("	   console.log(comment_idx);\r\n");
      out.write("	   console.log(board_idx);\r\n");
      out.write("	   console.log(user_name);\r\n");
      out.write("	   console.log(comment_content);\r\n");
      out.write("	   \r\n");
      out.write("		 $.ajax({\r\n");
      out.write("			 url : \"rereTestComment\",\r\n");
      out.write("			 data : {\r\n");
      out.write("				 comment_idx : comment_idx,\r\n");
      out.write("				 comment_nb : comment_nb,\r\n");
      out.write("				 board_idx : board_idx,\r\n");
      out.write("				 user_name : user_name,\r\n");
      out.write("				 comment_content : comment_content	 \r\n");
      out.write("			 },\r\n");
      out.write("			 type : \"Post\",\r\n");
      out.write("			 success : function(data){\r\n");
      out.write("				 $('#reContent').val('') //댓글 등록시 댓글 등록창 초기화\r\n");
      out.write("					getReplyList(); //등록후 댓글 목록 불러오기 함수 실행\r\n");
      out.write("			 }\r\n");
      out.write("		 })\r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write("//댓글 삭제\r\n");
      out.write(" $(document).on(\"click\",'button[name=\"butdel\"]',function(){\r\n");
      out.write("	// 댓글삭제 버튼의 ID에서 댓글 번호 추출\r\n");
      out.write("	   var comment_nb = $(this).attr('id').split('-')[2];//삭제할 댓글 의 고유값\r\n");
      out.write("		 $.ajax({\r\n");
      out.write("			 url : \"CommentDel\",\r\n");
      out.write("			 data : {\r\n");
      out.write("				 comment_nb : comment_nb\r\n");
      out.write("			 },\r\n");
      out.write("			 type : \"Post\",\r\n");
      out.write("			 success : function(data){\r\n");
      out.write("				 $('#reContent').val('') //댓글 등록시 댓글 등록창 초기화\r\n");
      out.write("					getReplyList(); //등록후 댓글 목록 불러오기 함수 실행\r\n");
      out.write("			 }\r\n");
      out.write("		 })\r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("//댓글 수정 text 열기\r\n");
      out.write("$(document).on(\"click\",'button[name=\"butmod\"]',function(){\r\n");
      out.write("	// 댓글삭제 버튼의 ID에서 댓글 번호 추출\r\n");
      out.write("	\r\n");
      out.write("	   	// 대댓글 작성 버튼의 ID에서 댓글 번호 추출\r\n");
      out.write(" 	    var commentIdx = $(this).attr('id').split('-')[2];\r\n");
      out.write(" 	    var dvreContmod = $('#dvreContmod' + commentIdx);\r\n");
      out.write(" 	    \r\n");
      out.write(" 	    // 현재 요소의 display 속성 값을 체크하여 보이게 하거나 숨기기\r\n");
      out.write(" 	    if (dvreContmod.css('display') === 'none') {\r\n");
      out.write(" 	    	dvreContmod.show();\r\n");
      out.write(" 	    } else {\r\n");
      out.write(" 	    	dvreContmod.hide();\r\n");
      out.write(" 	    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//댓글 수정하기\r\n");
      out.write("$(document).on(\"click\",'button[name=\"bsubmod\"]',function(){\r\n");
      out.write("	// 수정  버튼의 ID에서 댓글 번호 추출\r\n");
      out.write("	   var comment_nb = $(this).attr('id').split('-')[2];//내가 쓴 댓글 고유값\r\n");
      out.write("	   var comment_content = $(\"#reContentmod\"+comment_nb).val();\r\n");
      out.write("	   console.log(comment_nb);\r\n");
      out.write("	   console.log(comment_content);\r\n");
      out.write("	   \r\n");
      out.write("		 $.ajax({\r\n");
      out.write("			 url : \"CommentMod\",\r\n");
      out.write("			 data : {\r\n");
      out.write("				 comment_nb : comment_nb,\r\n");
      out.write("				 comment_content : comment_content	 \r\n");
      out.write("			 },\r\n");
      out.write("			 type : \"Post\",\r\n");
      out.write("			 success : function(data){\r\n");
      out.write("				 //$('#reContent').val('') //댓글 등록시 댓글 등록창 초기화\r\n");
      out.write("				  getReplyList(); //등록후 댓글 목록 불러오기 함수 실행\r\n");
      out.write("			 }\r\n");
      out.write("		 })\r\n");
      out.write("});\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" 	function getReplyList(){\r\n");
      out.write(" 		var board_idx = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write(" 		\r\n");
      out.write(" 		$.ajax({\r\n");
      out.write(" 			url : \"reTestCommentList\",\r\n");
      out.write(" 			type : \"Get\",\r\n");
      out.write(" 			dataType : \"json\",\r\n");
      out.write(" 			success : function(data){\r\n");
      out.write(" 				RList(data);\r\n");
      out.write(" 			}\r\n");
      out.write(" 		})\r\n");
      out.write(" 		\r\n");
      out.write(" 	}\r\n");
      out.write(" 	function RList(data){\r\n");
      out.write(" 		var html = \"\";   \r\n");
      out.write("         $.each(data, function(index , item){\r\n");
      out.write("        	 if(item.comment_grps !=1){\r\n");
      out.write("        		 html += '<div class=\"card bg-light\" style=\"width: 80%; float:right;>';\r\n");
      out.write("                 html += '<div class=\"d-flex mb-4\">'; \r\n");
      out.write("                 html += '<div class=\"flex-shrink-0\"  style = \"font-size:1.5em; color: green;\">'+ item.user_name +'</div>';\r\n");
      out.write("                 html += '<div class=\"ms-3\">';\r\n");
      out.write("                 html += '<div>' + item.comment_content + '</div>';\r\n");
      out.write("                 html += '<div>';\r\n");
      out.write("                if(item.comment_content != \"삭제되었습니다\"){\r\n");
      out.write("                     html += '<button type=\"button\" name=\"but\" style=\"margin : 10px;\" id=\"but-'+ item.comment_idx +\"-\"\r\n");
      out.write("                     + item.comment_nb +'\"</button>대댓글쓰기'\r\n");
      out.write("               	if(item.user_name == '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'){\r\n");
      out.write("               		html += '<button type=\"button\" name=\"butdel\" style=\"margin : 10px;\" id=\"butdel-'+ item.comment_idx +\"-\"\r\n");
      out.write("                    + item.comment_nb +'\"</button>댓글 삭제'\r\n");
      out.write("                    html += '<button type=\"button\" name=\"butmod\" style=\"margin : 10px;\" id=\"butmod-'+ item.comment_idx +\"-\"\r\n");
      out.write("                    + item.comment_nb +'\"</button>댓글 수정'\r\n");
      out.write("               	}\r\n");
      out.write("                }\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 \r\n");
      out.write("                 html += '<div style=\"text-align: right; display: none;\" id=\"dvreCont'+item.comment_nb+'\">';\r\n");
      out.write("                 html += '<textarea class=\"form-control\"  rows=\"1\" id=\"reContent'+item.comment_nb+'\"></textarea>'  \r\n");
      out.write("                 html += '<button type=\"button\" name=\"bsub\" id=\"bsub-'+ item.comment_idx +\"-\"\r\n");
      out.write("                 + item.comment_nb +'\"style=\"padding: 15px; margin: 20px;\">등록</button>'	\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 \r\n");
      out.write("                 html += '<div style=\"text-align: right; display: none;\" id=\"dvreContmod'+item.comment_nb+'\">';\r\n");
      out.write("                 html += '<textarea class=\"form-control\"  rows=\"1\" id=\"reContentmod'+item.comment_nb+'\"></textarea>'  \r\n");
      out.write("                 html += '<button type=\"button\" name=\"bsubmod\" id=\"bsubmod-'+ item.comment_idx +\"-\"\r\n");
      out.write("                 + item.comment_nb +'\"style=\"padding: 15px; margin: 20px;\">수정</button>'	\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 \r\n");
      out.write("                 html += '</div>'; \r\n");
      out.write("        	 }else{\r\n");
      out.write("        		 html += '<div class=\"card bg-light\" style=\"width: 100%;>';\r\n");
      out.write("                 html += '<div class=\"d-flex mb-4\">'; \r\n");
      out.write("                 html += '<div class=\"flex-shrink-0\"  style = \"font-size:1.5em; color: green;\">'+ item.user_name +'</div>';\r\n");
      out.write("                 html += '<div class=\"ms-3\">';\r\n");
      out.write("                 html += '<div>' + item.comment_content + '</div>';\r\n");
      out.write("                 html += '<div>';\r\n");
      out.write("                if(item.comment_content != \"삭제되었습니다\"){\r\n");
      out.write("                     html += '<button type=\"button\" name=\"but\" style=\"margin : 10px;\" id=\"but-'+ item.comment_idx +\"-\"\r\n");
      out.write("                     + item.comment_nb +'\"</button>대댓글쓰기'\r\n");
      out.write("               	if(item.user_name == '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'){\r\n");
      out.write("               		html += '<button type=\"button\" name=\"butdel\" style=\"margin : 10px;\" id=\"butdel-'+ item.comment_idx +\"-\"\r\n");
      out.write("                    + item.comment_nb +'\"</button>댓글 삭제'\r\n");
      out.write("                    html += '<button type=\"button\" name=\"butmod\" style=\"margin : 10px;\" id=\"butmod-'+ item.comment_idx +\"-\"\r\n");
      out.write("                    + item.comment_nb +'\"</button>댓글 수정'\r\n");
      out.write("               	}\r\n");
      out.write("                }\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 \r\n");
      out.write("                 html += '<div style=\"text-align: right; display: none;\" id=\"dvreCont'+item.comment_nb+'\">';\r\n");
      out.write("                 html += '<textarea class=\"form-control\"  rows=\"1\" id=\"reContent'+item.comment_nb+'\"></textarea>'  \r\n");
      out.write("                 html += '<button type=\"button\" name=\"bsub\" id=\"bsub-'+ item.comment_idx +\"-\"\r\n");
      out.write("                 + item.comment_nb +'\"style=\"padding: 15px; margin: 20px;\">등록</button>'	\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 \r\n");
      out.write("                 html += '<div style=\"text-align: right; display: none;\" id=\"dvreContmod'+item.comment_nb+'\">';\r\n");
      out.write("                 html += '<textarea class=\"form-control\"  rows=\"1\" id=\"reContentmod'+item.comment_nb+'\"></textarea>'  \r\n");
      out.write("                 html += '<button type=\"button\" name=\"bsubmod\" id=\"bsubmod-'+ item.comment_idx +\"-\"\r\n");
      out.write("                 + item.comment_nb +'\"style=\"padding: 15px; margin: 20px;\">수정</button>'	\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 \r\n");
      out.write("                 html += '</div>'; \r\n");
      out.write("        	 }\r\n");
      out.write("\r\n");
      out.write("          // 생성한 HTML 코드를 원하는 곳에 삽입\r\n");
      out.write("             $('#card-bodyo').html(html);\r\n");
      out.write("         })\r\n");
      out.write(" 	}\r\n");
      out.write(" </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
