/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.83
 * Generated at: 2023-04-14 00:52:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.JUS;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/JUS/work/DevfoxProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/DevJUS/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1672725238227L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("		<!-- Bootstrap ! -->\r\n");
      out.write("  		<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ\" crossorigin=\"anonymous\">\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"/resources/css/styles.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("        <!--navbar-->\r\n");
      out.write("        <nav class=\"navbar navbar-light bg-light static-top\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"index\">모임나라</a>\r\n");
      out.write("                <div style=\"text-align: right;\">\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		 ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        <a href=\"board\">게시판으로</a>\r\n");
      out.write("             	</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- Page Content-->\r\n");
      out.write("        <div class=\"container px-4 px-lg-5\">\r\n");
      out.write("            <!-- Heading Row-->\r\n");
      out.write("            <div class=\"row gx-4 gx-lg-5 align-items-center my-5\">\r\n");
      out.write("                <div class=\"col-lg-7\"><img class=\"img-fluid rounded mb-4 mb-lg-0\" src=\"/img/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_poto_new}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"...\" /></div>\r\n");
      out.write("                <div class=\"col-lg-5\" id=\"title\">\r\n");
      out.write("                    <h2 class=\"font-weight-light\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("                    <h3>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("                    <h4>시작일 :  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_period_start}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" / 종료일 :  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_period_end}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("                    <h4 id=\"limitday\">마감인원 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_limit}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("  / 신청인원 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.request_order}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("                    \r\n");
      out.write("                  ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                  ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                   \r\n");
      out.write("                   ");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                   ");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                     \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card text-white bg-secondary my-5 py-4\">\r\n");
      out.write("                <div class=\"card-body\">\r\n");
      out.write("                \r\n");
      out.write("                <h1 class=\"text-white m-0\">주최자 닉네임 :   ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("                \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Content Row-->\r\n");
      out.write("            <div class=\"row gx-4 gx-lg-5\">\r\n");
      out.write("                <div class=\"col-md-4 mb-5\">\r\n");
      out.write("                    <div class=\"card h-100\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <h2 class=\"card-title\">만나는 요일</h2>\r\n");
      out.write("                            <h3 class=\"card-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_days}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4 mb-5\">\r\n");
      out.write("                    <div class=\"card h-100\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <h2 class=\"card-title\">장소</h2>\r\n");
      out.write("                            <h3 class=\"card-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4 mb-5\">\r\n");
      out.write("                    <div class=\"card h-100\">\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <h2 class=\"card-title\">신청마감</h2>\r\n");
      out.write("                            <h3 class=\"card-text\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_end}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 까지</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("         <!-- Comments section-->\r\n");
      out.write("         <section class=\"mb-5\">\r\n");
      out.write("            <div class=\"card bg-light\">\r\n");
      out.write("               <div class=\"card-body\" >\r\n");
      out.write("				<input type=\"hidden\" name=\"board_idx\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_idx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<input type=\"hidden\" name=\"user_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                     <textarea class=\"form-control\" rows=\"1\" id=\"reContent\"></textarea>\r\n");
      out.write("                          <div style=\"text-align: right;\">\r\n");
      out.write("                           <button type=\"button\" id=\"bsub\" style=\"padding: 15px; margin: 20px;\">등록</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                         <!-- Comment with nested comments-->\r\n");
      out.write("                            <div id=\"card-bodyo\">\r\n");
      out.write("                            \r\n");
      out.write("                            </div>    \r\n");
      out.write(" \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <div id=\"oup2\">\r\n");
      out.write("				<div\r\n");
      out.write("					style=\"position: relative; min-height: 100px; margin-top: 12px; border: 1px solid #b3b3b3; box-sizing: border-box;\">\r\n");
      out.write("					<nav aria-label=\"Page navigation example\">\r\n");
      out.write("						<ul class=\"pagination justify-content-center pagination-xl\">\r\n");
      out.write("							\r\n");
      out.write("							\r\n");
      out.write("						</ul>\r\n");
      out.write("					</nav>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("                    </section>\r\n");
      out.write("         </div>\r\n");
      out.write("        <!-- Footer-->\r\n");
      out.write("        <footer class=\"py-5 bg-dark\">\r\n");
      out.write("            <div class=\"container px-4 px-lg-5\"><p class=\"m-0 text-center text-white\">Copyright &copy; Your Website 2023</p></div>\r\n");
      out.write("        </footer>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	//신청버튼 이벤트\r\n");
      out.write("	$(\"#request\").click(function() {\r\n");
      out.write("		var requestvalue  = $('#request').data('value');\r\n");
      out.write("		console.log(requestvalue);\r\n");
      out.write("		  var user_name = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		  var board_idx = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		  var request_user = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		 if(requestvalue == 0){\r\n");
      out.write("			 $.ajax({\r\n");
      out.write("					url: \"view_request\" ,\r\n");
      out.write("					type: \"Post\",\r\n");
      out.write("					dataType: \"text\",\r\n");
      out.write("					data: { \r\n");
      out.write("						user_name: user_name,\r\n");
      out.write("						board_idx : board_idx,\r\n");
      out.write("						request_user : request_user\r\n");
      out.write("						},\r\n");
      out.write("					success: function(data) {\r\n");
      out.write("						console.log(data+\"성공\");\r\n");
      out.write("						$(\"#request\").text(\"신청취소\");\r\n");
      out.write("						$(\"#request\").css(\"background-color\", \"red\" , \"color\" , \"white\");\r\n");
      out.write("						$(\"#request\").data(\"value\", 1);\r\n");
      out.write("						$(\"#limitday\").text(\"마감인원 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_limit}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("  / 신청인원 : \"+data);\r\n");
      out.write("						\r\n");
      out.write("						}\r\n");
      out.write("				  })\r\n");
      out.write("		 }else{\r\n");
      out.write("			 $.ajax({\r\n");
      out.write("					url: \"view_request_m\" ,\r\n");
      out.write("					type: \"Post\",\r\n");
      out.write("					dataType: \"text\",\r\n");
      out.write("					data: { \r\n");
      out.write("						board_idx : board_idx,\r\n");
      out.write("						request_user : request_user\r\n");
      out.write("						},\r\n");
      out.write("					success: function(data) {\r\n");
      out.write("						console.log(\"성공\");\r\n");
      out.write("						$(\"#request\").text(\"신청하기\");\r\n");
      out.write("						$(\"#request\").css(\"background-color\", \"blue\", \"color\" , \"white\");\r\n");
      out.write("						$(\"#request\").data(\"value\", 0);\r\n");
      out.write("						$(\"#limitday\").text(\"마감인원 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_limit}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("  / 신청인원 : \"+data);\r\n");
      out.write("						}\r\n");
      out.write("				  })\r\n");
      out.write("		 }\r\n");
      out.write("		  \r\n");
      out.write("		\r\n");
      out.write("		});\r\n");
      out.write("	\r\n");
      out.write("	//추천버튼\r\n");
      out.write("	$(\"#recommend\").click(function() {\r\n");
      out.write("		  var user_name = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		  var board_idx = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		  var recommend_user = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		  var recommendButton = $('#recommend');\r\n");
      out.write("\r\n");
      out.write("		  $.ajax({\r\n");
      out.write("				url: \"view_recommend\",\r\n");
      out.write("				type: \"Post\",\r\n");
      out.write("				dataType: \"text\",\r\n");
      out.write("				data: { \r\n");
      out.write("					user_name: user_name,\r\n");
      out.write("					board_idx : board_idx,\r\n");
      out.write("					recommend_user : recommend_user\r\n");
      out.write("					},\r\n");
      out.write("				success: function(data) {\r\n");
      out.write("					if(data ==0){\r\n");
      out.write("						alert(\"이미 추천하셨습니다\")\r\n");
      out.write("					}else{\r\n");
      out.write("						$(\"#recommend img\").attr(\"src\", \"/resources/css/img/heartsX.png\");\r\n");
      out.write("						$(\"#recommend span\").text(data);\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("					}\r\n");
      out.write("			  })\r\n");
      out.write("		  \r\n");
      out.write("	})\r\n");
      out.write("	 var TotList = []; // 댓글 리스트  배열\r\n");
      out.write("	 var pageCount = 0; // 총 페이지\r\n");
      out.write("	 var startPage = 0;//시작 번호\r\n");
      out.write("	 var endPage =10 // 마지막 번호\r\n");
      out.write("	 var totPage = 0;//	\r\n");
      out.write("	 var nowPage = 1;//현재 페이지\r\n");
      out.write("	 var pagination = $(\"#oup2 .pagination\");// 버튼 추가 자리\r\n");
      out.write("	 var prevBtn = $(\"<li class='page-item page-link' id='prevBtn'>&laquo;</li>\");\r\n");
      out.write("	 var nextBtn = $(\"<li class='page-item page-link' id='nextBtn'>&raquo;</li>\");//다음버튼\r\n");
      out.write("		\r\n");
      out.write("		// 페이지 버튼 생성 함수\r\n");
      out.write("	            function createPageButton(pageNum) {\r\n");
      out.write("			\r\n");
      out.write("				var pageLink = $(\"<li class='page-link os'></li>\").text(pageNum).attr('value', pageNum);\r\n");
      out.write("				\r\n");
      out.write("				  if (pageNum == nowPage ) {\r\n");
      out.write("					    pageLink.css('color', 'red');\r\n");
      out.write("					  }\r\n");
      out.write("\r\n");
      out.write("	            var pageBtn = $(\"<li class='page-item'></li>\").append(pageLink);\r\n");
      out.write("	              return pageBtn;\r\n");
      out.write("	 }\r\n");
      out.write("		// 페이지 버튼 보이기/숨기기 처리 함수\r\n");
      out.write("	     function setPageButtonVisibility(start, end) {\r\n");
      out.write("	  	pagination.find('.page-item').remove();\r\n");
      out.write("			if (pageCount > 1) {\r\n");
      out.write("			    for (var i = start; i <= Math.min(end, 10); i++) {\r\n");
      out.write("			      pagination.find('.page-item:nth-child(' + i + ')').show();\r\n");
      out.write("			    }\r\n");
      out.write("\r\n");
      out.write("				 }\r\n");
      out.write("			// 페이지 버튼 추가\r\n");
      out.write("			if(pageCount > 1) {\r\n");
      out.write("				pagination.empty();\r\n");
      out.write("				pagination.append(prevBtn);\r\n");
      out.write("	      	for (var i = 1; i <= Math.min(end, 10)  ; i++) {\r\n");
      out.write("	       	 pagination.append(createPageButton(i));\r\n");
      out.write("	       		//pagetotcount++;\r\n");
      out.write("	    		  }\r\n");
      out.write("	      	\r\n");
      out.write("	      	 pagination.append(nextBtn);\r\n");
      out.write("			}else{\r\n");
      out.write("				pagination.empty()\r\n");
      out.write("				pagination.append(createPageButton(1));\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			}\r\n");
      out.write("//페이지 로딩시		\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("	 if (sessionStorage.getItem('user')  === 'undefined') { // 세션 확ㅌ인\r\n");
      out.write("		    window.location.href = 'index'; // 이동할 페이지 URL\r\n");
      out.write("		  }\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	 $.ajax({\r\n");
      out.write("		 url: \"CommentList\",\r\n");
      out.write("		 type: \"get\",\r\n");
      out.write("		 contentType: \"application/json; charset=UTF-8\",\r\n");
      out.write("		 dataType: \"json\",\r\n");
      out.write("		 success: function(data){\r\n");
      out.write("			 \r\n");
      out.write("			 TotList = data;\r\n");
      out.write("			 Listsize = TotList.length;\r\n");
      out.write("			// 페이지 수 계산\r\n");
      out.write("	        pageCount = Math.ceil(Listsize / 10);\r\n");
      out.write("	        console.log(pageCount);\r\n");
      out.write("\r\n");
      out.write("         	// 페이지 버튼 보이기/숨기기 처리\r\n");
      out.write("            setPageButtonVisibility(1, pageCount);\r\n");
      out.write("\r\n");
      out.write("	        RList(data)\r\n");
      out.write("    \r\n");
      out.write("	 	}\r\n");
      out.write(" 	})\r\n");
      out.write(" 	 \r\n");
      out.write("	 \r\n");
      out.write("	 \r\n");
      out.write(" 	//페이지 클릭시\r\n");
      out.write(" 	$(document).on('click', '.os', function() {\r\n");
      out.write(" 		\r\n");
      out.write(" 		nowPage = $(this).val();//가져온 페이지 번호\r\n");
      out.write(" 		startPage = (nowPage - 1) * 10 //시작 번호\r\n");
      out.write(" 		$.ajax({\r\n");
      out.write(" 			url: \"commentPage\",\r\n");
      out.write(" 			data :{\r\n");
      out.write(" 				startPage : startPage\r\n");
      out.write(" 			},\r\n");
      out.write(" 			type : \"get\",\r\n");
      out.write(" 			success : function(data){\r\n");
      out.write(" 				\r\n");
      out.write("\r\n");
      out.write("				// 페이지 수 계산\r\n");
      out.write("		        pageCount = Math.ceil(data.size / 10);\r\n");
      out.write("		        console.log(pageCount);\r\n");
      out.write("\r\n");
      out.write("	         	// 페이지 버튼 보이기/숨기기 처리\r\n");
      out.write("	            setPageButtonVisibility(1, pageCount);\r\n");
      out.write("	         	\r\n");
      out.write("				 $('#reContent').val('') //댓글 등록시 댓글 등록창 초기화\r\n");
      out.write("					 RList(data.list) //등록후 댓글 목록 불러오기 함수 실행\r\n");
      out.write(" 			}\r\n");
      out.write(" 			\r\n");
      out.write(" 		\r\n");
      out.write(" 		})\r\n");
      out.write(" 	})\r\n");
      out.write(" 	\r\n");
      out.write(" })\r\n");
      out.write(" //대댓글 버튼 누를시\r\n");
      out.write(" $(document).on(\"click\",'button[name=\"but\"]',function() {\r\n");
      out.write(" 	    // 대댓글 작성 버튼의 ID에서 댓글 번호 추출\r\n");
      out.write(" 	    var commentIdx = $(this).attr('id').split('-')[2];\r\n");
      out.write(" 	    var dvreCont = $('#dvreCont' + commentIdx);\r\n");
      out.write(" 	    \r\n");
      out.write(" 	    // 현재 요소의 display 속성 값을 체크하여 보이게 하거나 숨기기\r\n");
      out.write(" 	    if (dvreCont.css('display') === 'none') {\r\n");
      out.write(" 	    	dvreCont.show();\r\n");
      out.write(" 	    } else {\r\n");
      out.write(" 	    	dvreCont.hide();\r\n");
      out.write(" 	    }\r\n");
      out.write(" 	});\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" //댓글 insert\r\n");
      out.write(" $('#bsub').on(\"click\", function() {\r\n");
      out.write("	 var board_idx = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("	 var user_name = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("	 var comment_content = $(\"#reContent\").val();\r\n");
      out.write("	 console.log(board_idx);\r\n");
      out.write("	 console.log(comment_content);\r\n");
      out.write("	 console.log(user_name);\r\n");
      out.write("	 $.ajax({\r\n");
      out.write("		 url : \"reTestComment\",\r\n");
      out.write("		 data : {\r\n");
      out.write("			 board_idx : board_idx,\r\n");
      out.write("			 comment_content : comment_content,\r\n");
      out.write("			 user_name : user_name\r\n");
      out.write("		 },\r\n");
      out.write("		 type : \"Post\",\r\n");
      out.write("		 success : function(data){\r\n");
      out.write("			 console.log(\"성공\")\r\n");
      out.write("			 \r\n");
      out.write("			 TotList = data;\r\n");
      out.write("			 Listsize = TotList.length;\r\n");
      out.write("			// 페이지 수 계산\r\n");
      out.write("	        pageCount = Math.ceil(Listsize / 10);\r\n");
      out.write("	        console.log(pageCount);\r\n");
      out.write("	        nowPage = pageCount;\r\n");
      out.write("         	// 페이지 버튼 보이기/숨기기 처리\r\n");
      out.write("            setPageButtonVisibility(1, pageCount);\r\n");
      out.write("			 \r\n");
      out.write("			 $('#reContent').val('') //댓글 등록시 댓글 등록창 초기화\r\n");
      out.write("			\r\n");
      out.write("				getReplyList(); //등록후 마지막 댓글 목록 불러오기 함수 실행\r\n");
      out.write("				\r\n");
      out.write("		 }\r\n");
      out.write("	 })\r\n");
      out.write(" });\r\n");
      out.write(" //대댓글 등록\r\n");
      out.write(" $(document).on(\"click\",'button[name=\"bsub\"]',function(){\r\n");
      out.write("	// 대댓글 등록 버튼의 ID에서 댓글 번호 추출\r\n");
      out.write("	  \r\n");
      out.write("	   var comment_idx = $(this).attr('id').split('-')[1];//부모 댓글 idx\r\n");
      out.write("	   var comment_nb = $(this).attr('id').split('-')[2];//대댓글 위사람\r\n");
      out.write("	   var board_idx = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"// 글 idx\r\n");
      out.write("	   var user_name = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" // 댓글 작성유저\r\n");
      out.write("	   var comment_content = $(\"#reContent\"+comment_nb).val();\r\n");
      out.write("	   console.log(comment_idx);\r\n");
      out.write("	   console.log(board_idx);\r\n");
      out.write("	   console.log(user_name);\r\n");
      out.write("	   console.log(comment_content);\r\n");
      out.write("	   \r\n");
      out.write("		 $.ajax({\r\n");
      out.write("			 url : \"rereTestComment\",\r\n");
      out.write("			 data : {\r\n");
      out.write("				 nowPage :nowPage,\r\n");
      out.write("				 comment_idx : comment_idx,\r\n");
      out.write("				 comment_nb : comment_nb,\r\n");
      out.write("				 board_idx : board_idx,\r\n");
      out.write("				 user_name : user_name,\r\n");
      out.write("				 comment_content : comment_content	 \r\n");
      out.write("			 },\r\n");
      out.write("			 type : \"Post\",\r\n");
      out.write("			 success : function(data){\r\n");
      out.write("				 \r\n");
      out.write("\r\n");
      out.write("				// 페이지 수 계산\r\n");
      out.write("		        pageCount = Math.ceil(data.size / 10);\r\n");
      out.write("		        console.log(pageCount);\r\n");
      out.write("\r\n");
      out.write("	         	// 페이지 버튼 보이기/숨기기 처리\r\n");
      out.write("	            setPageButtonVisibility(1, pageCount);\r\n");
      out.write("	         	\r\n");
      out.write("				 $('#reContent').val('') //댓글 등록시 댓글 등록창 초기화\r\n");
      out.write("					 RList(data.startList) //등록후 댓글 목록 불러오기 함수 실행\r\n");
      out.write("			 }\r\n");
      out.write("		 })\r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write("//댓글 삭제\r\n");
      out.write(" $(document).on(\"click\",'button[name=\"butdel\"]',function(){\r\n");
      out.write("	// 댓글삭제 버튼의 ID에서 댓글 번호 추출\r\n");
      out.write("	   var comment_nb = $(this).attr('id').split('-')[2];//삭제할 댓글 의 고유값\r\n");
      out.write("		 $.ajax({\r\n");
      out.write("			 url : \"CommentDel\",\r\n");
      out.write("			 data : {\r\n");
      out.write("				 nowPage : nowPage,\r\n");
      out.write("				 comment_nb : comment_nb\r\n");
      out.write("			 },\r\n");
      out.write("			 type : \"Post\",\r\n");
      out.write("			 success : function(data){\r\n");
      out.write("				// 페이지 수 계산\r\n");
      out.write("			     pageCount = Math.ceil(data.size / 10);\r\n");
      out.write("			     console.log(pageCount);\r\n");
      out.write("\r\n");
      out.write("		        // 페이지 버튼 보이기/숨기기 처리\r\n");
      out.write("		          setPageButtonVisibility(1, pageCount);\r\n");
      out.write("		         	\r\n");
      out.write("				  $('#reContent').val('') //댓글 등록시 댓글 등록창 초기화\r\n");
      out.write("				   RList(data.startList) //등록후 댓글 목록 불러오기 함수 실행\r\n");
      out.write("			 }\r\n");
      out.write("		 })\r\n");
      out.write(" });\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("//댓글 수정 text 열기\r\n");
      out.write("$(document).on(\"click\",'button[name=\"butmod\"]',function(){\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	   	// 대댓글 작성 버튼의 ID에서 댓글 번호 추출\r\n");
      out.write(" 	    var commentIdx = $(this).attr('id').split('-')[2];\r\n");
      out.write(" 	    var dvreContmod = $('#dvreContmod' + commentIdx);\r\n");
      out.write(" 	    \r\n");
      out.write(" 	    // 현재 요소의 display 속성 값을 체크하여 보이게 하거나 숨기기\r\n");
      out.write(" 	    if (dvreContmod.css('display') === 'none') {\r\n");
      out.write(" 	    	dvreContmod.show();\r\n");
      out.write(" 	    } else {\r\n");
      out.write(" 	    	dvreContmod.hide();\r\n");
      out.write(" 	    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//댓글 수정하기\r\n");
      out.write("$(document).on(\"click\",'button[name=\"bsubmod\"]',function(){\r\n");
      out.write("	// 수정  버튼의 ID에서 댓글 번호 추출\r\n");
      out.write("	   var comment_nb = $(this).attr('id').split('-')[2];//내가 쓴 댓글 고유값\r\n");
      out.write("	   var comment_content = $(\"#reContentmod\"+comment_nb).val();\r\n");
      out.write("	   console.log(comment_nb);\r\n");
      out.write("	   console.log(comment_content);\r\n");
      out.write("	   \r\n");
      out.write("		 $.ajax({\r\n");
      out.write("			 url : \"CommentMod\",\r\n");
      out.write("			 data : {\r\n");
      out.write("				 nowPage : nowPage,\r\n");
      out.write("				 comment_nb : comment_nb,\r\n");
      out.write("				 comment_content : comment_content	 \r\n");
      out.write("			 },\r\n");
      out.write("			 type : \"Post\",\r\n");
      out.write("			 success : function(data){\r\n");
      out.write("					// 페이지 수 계산\r\n");
      out.write("			     pageCount = Math.ceil(data.size / 10);\r\n");
      out.write("			     console.log(pageCount);\r\n");
      out.write("\r\n");
      out.write("		        // 페이지 버튼 보이기/숨기기 처리\r\n");
      out.write("		          setPageButtonVisibility(1, pageCount);\r\n");
      out.write("		         	\r\n");
      out.write("				  $('#reContent').val('') //댓글 등록시 댓글 등록창 초기화\r\n");
      out.write("				   RList(data.startList) //등록후 댓글 목록 불러오기 함수 실행\r\n");
      out.write("			 }\r\n");
      out.write("		 })\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//전 버튼 클릭시\r\n");
      out.write("$(document).on('click', '#prevBtn', function() {\r\n");
      out.write("\r\n");
      out.write("	nowPage = nowPage -1; // 다음페이지\r\n");
      out.write("	if(nowPage == 0){\r\n");
      out.write("		nowPage = 1;\r\n");
      out.write("	}\r\n");
      out.write("	console.log(nowPage);\r\n");
      out.write("	startPage = (nowPage - 1) * 10; //시작 번호\r\n");
      out.write("		console.log(startPage);\r\n");
      out.write("		$.ajax({\r\n");
      out.write(" 			url: \"commentPage\",\r\n");
      out.write(" 			data :{\r\n");
      out.write(" 				startPage : startPage\r\n");
      out.write(" 			},\r\n");
      out.write(" 			type : \"get\",\r\n");
      out.write(" 			success : function(data){\r\n");
      out.write(" 				\r\n");
      out.write("\r\n");
      out.write("				// 페이지 수 계산\r\n");
      out.write("		        pageCount = Math.ceil(data.size / 10);\r\n");
      out.write("		        console.log(pageCount);\r\n");
      out.write("\r\n");
      out.write("	         	// 페이지 버튼 보이기/숨기기 처리\r\n");
      out.write("	            setPageButtonVisibility(1, pageCount);\r\n");
      out.write("	         	\r\n");
      out.write("				 $('#reContent').val('') //댓글 등록시 댓글 등록창 초기화\r\n");
      out.write("					 RList(data.list) //등록후 댓글 목록 불러오기 함수 실행\r\n");
      out.write(" 			}\r\n");
      out.write(" 			\r\n");
      out.write(" 		\r\n");
      out.write(" 		})\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("//다음 버튼 클릭시\r\n");
      out.write("$(document).on('click', '#nextBtn', function() {\r\n");
      out.write("\r\n");
      out.write("	nowPage = nowPage + 1; // 다음페이지\r\n");
      out.write("	if(nowPage >= pageCount){\r\n");
      out.write("		nowPage = pageCount;\r\n");
      out.write("	}\r\n");
      out.write("	console.log(nowPage);\r\n");
      out.write("	startPage = (nowPage - 1) * 10; //시작 번호\r\n");
      out.write("		console.log(startPage);\r\n");
      out.write("		$.ajax({\r\n");
      out.write(" 			url: \"commentPage\",\r\n");
      out.write(" 			data :{\r\n");
      out.write(" 				startPage : startPage\r\n");
      out.write(" 			},\r\n");
      out.write(" 			type : \"get\",\r\n");
      out.write(" 			success : function(data){\r\n");
      out.write(" 				\r\n");
      out.write("\r\n");
      out.write("				// 페이지 수 계산\r\n");
      out.write("		        pageCount = Math.ceil(data.size / 10);\r\n");
      out.write("		        console.log(pageCount);\r\n");
      out.write("\r\n");
      out.write("	         	// 페이지 버튼 보이기/숨기기 처리\r\n");
      out.write("	            setPageButtonVisibility(1, pageCount);\r\n");
      out.write("	         	\r\n");
      out.write("				 $('#reContent').val('') //댓글 등록시 댓글 등록창 초기화\r\n");
      out.write("					 RList(data.list) //등록후 댓글 목록 불러오기 함수 실행\r\n");
      out.write(" 			}\r\n");
      out.write(" 			\r\n");
      out.write(" 		\r\n");
      out.write(" 		})\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write(" 	function getReplyList(){\r\n");
      out.write(" 		\r\n");
      out.write(" 		$.ajax({\r\n");
      out.write(" 			url : \"Commint_insert_list\",\r\n");
      out.write(" 			type : \"Get\",\r\n");
      out.write(" 			dataType : \"json\",\r\n");
      out.write(" 			success : function(data){\r\n");
      out.write(" 				RList(data);\r\n");
      out.write(" 			}\r\n");
      out.write(" 		})\r\n");
      out.write(" 		\r\n");
      out.write(" 	}\r\n");
      out.write(" 	function RList(data){\r\n");
      out.write(" 		var html = \"\";   \r\n");
      out.write("         $.each(data.slice(0, 10), function(index , item){\r\n");
      out.write("        	 if(item.comment_grps !=1){\r\n");
      out.write("        		 html += '<div class=\"card bg-light\" style=\"width: 80%; float:right;>';\r\n");
      out.write("                 html += '<div class=\"d-flex mb-4\">'; \r\n");
      out.write("                 html += '<div class=\"flex-shrink-0\"  style = \"font-size:1.5em; color: green;\">'+ item.user_name +'</div>';\r\n");
      out.write("                 html += '<div class=\"ms-3\">';\r\n");
      out.write("                 html += '<div>' + item.comment_content + '</div>';\r\n");
      out.write("                 html += '<div>';\r\n");
      out.write("                if(item.comment_content != \"삭제되었습니다\"){\r\n");
      out.write("                     html += '<button type=\"button\" name=\"but\" style=\"margin : 10px;\" id=\"but-'+ item.comment_idx +\"-\"\r\n");
      out.write("                     + item.comment_nb +'\"</button>대댓글쓰기'\r\n");
      out.write("               	if(item.user_name == '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'){\r\n");
      out.write("               		html += '<button type=\"button\" name=\"butdel\" style=\"margin : 10px;\" id=\"butdel-'+ item.comment_idx +\"-\"\r\n");
      out.write("                    + item.comment_nb +'\"</button>댓글 삭제'\r\n");
      out.write("                    html += '<button type=\"button\" name=\"butmod\" style=\"margin : 10px;\" id=\"butmod-'+ item.comment_idx +\"-\"\r\n");
      out.write("                    + item.comment_nb +'\"</button>댓글 수정'\r\n");
      out.write("               	}\r\n");
      out.write("                }\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 \r\n");
      out.write("                 html += '<div style=\"text-align: right; display: none;\" id=\"dvreCont'+item.comment_nb+'\">';\r\n");
      out.write("                 html += '<textarea class=\"form-control\"  rows=\"1\" id=\"reContent'+item.comment_nb+'\"></textarea>'  \r\n");
      out.write("                 html += '<button type=\"button\" name=\"bsub\" id=\"bsub-'+ item.comment_idx +\"-\"\r\n");
      out.write("                 + item.comment_nb +'\"style=\"padding: 15px; margin: 20px;\">등록</button>'	\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 \r\n");
      out.write("                 html += '<div style=\"text-align: right; display: none;\" id=\"dvreContmod'+item.comment_nb+'\">';\r\n");
      out.write("                 html += '<textarea class=\"form-control\"  rows=\"1\" id=\"reContentmod'+item.comment_nb+'\"></textarea>'  \r\n");
      out.write("                 html += '<button type=\"button\" name=\"bsubmod\" id=\"bsubmod-'+ item.comment_idx +\"-\"\r\n");
      out.write("                 + item.comment_nb +'\"style=\"padding: 15px; margin: 20px;\">수정</button>'	\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 \r\n");
      out.write("                 html += '</div>'; \r\n");
      out.write("        	 }else{\r\n");
      out.write("        		 html += '<div class=\"card bg-light\" style=\"width: 100%;>';\r\n");
      out.write("                 html += '<div class=\"d-flex mb-4\">'; \r\n");
      out.write("                 html += '<div class=\"flex-shrink-0\"  style = \"font-size:1.5em; color: green;\">'+ item.user_name +'</div>';\r\n");
      out.write("                 html += '<div class=\"ms-3\">';\r\n");
      out.write("                 html += '<div>' + item.comment_content + '</div>';\r\n");
      out.write("                 html += '<div>';\r\n");
      out.write("                if(item.comment_content != \"삭제되었습니다\"){\r\n");
      out.write("                     html += '<button type=\"button\" name=\"but\" style=\"margin : 10px;\" id=\"but-'+ item.comment_idx +\"-\"\r\n");
      out.write("                     + item.comment_nb +'\"</button>대댓글쓰기'\r\n");
      out.write("               	if(item.user_name == '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'){\r\n");
      out.write("               		html += '<button type=\"button\" name=\"butdel\" style=\"margin : 10px;\" id=\"butdel-'+ item.comment_idx +\"-\"\r\n");
      out.write("                    + item.comment_nb +'\"</button>댓글 삭제'\r\n");
      out.write("                    html += '<button type=\"button\" name=\"butmod\" style=\"margin : 10px;\" id=\"butmod-'+ item.comment_idx +\"-\"\r\n");
      out.write("                    + item.comment_nb +'\"</button>댓글 수정'\r\n");
      out.write("               	}\r\n");
      out.write("                }\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 \r\n");
      out.write("                 html += '<div style=\"text-align: right; display: none;\" id=\"dvreCont'+item.comment_nb+'\">';\r\n");
      out.write("                 html += '<textarea class=\"form-control\"  rows=\"1\" id=\"reContent'+item.comment_nb+'\"></textarea>'  \r\n");
      out.write("                 html += '<button type=\"button\" name=\"bsub\" id=\"bsub-'+ item.comment_idx +\"-\"\r\n");
      out.write("                 + item.comment_nb +'\"style=\"padding: 15px; margin: 20px;\">등록</button>'	\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 \r\n");
      out.write("                 html += '<div style=\"text-align: right; display: none;\" id=\"dvreContmod'+item.comment_nb+'\">';\r\n");
      out.write("                 html += '<textarea class=\"form-control\"  rows=\"1\" id=\"reContentmod'+item.comment_nb+'\"></textarea>'  \r\n");
      out.write("                 html += '<button type=\"button\" name=\"bsubmod\" id=\"bsubmod-'+ item.comment_idx +\"-\"\r\n");
      out.write("                 + item.comment_nb +'\"style=\"padding: 15px; margin: 20px;\">수정</button>'	\r\n");
      out.write("                 html += '</div>';\r\n");
      out.write("                 \r\n");
      out.write("                 html += '</div>'; \r\n");
      out.write("        	 }\r\n");
      out.write("\r\n");
      out.write("          // 생성한 HTML 코드를 원하는 곳에 삽입\r\n");
      out.write("             $('#card-bodyo').html(html);\r\n");
      out.write("         })\r\n");
      out.write(" 	}\r\n");
      out.write("</script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/JUS/view.jsp(21,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_power == 'x'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- user -->\r\n");
          out.write("				<a href=\"info\" ><img src=\"/resources/css/img/user.png\" alt=\"\" style=\"width: 10%;\"></a>\r\n");
          out.write("				<a href=\"index\" ><img src=\"/resources/css/img/logout.png\" alt=\"\" style=\"width: 10%;\"></a>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/JUS/view.jsp(25,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_power == 'o'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- admin -->\r\n");
          out.write("				<a href=\"info\" >관리자</a>\r\n");
          out.write("				<a href=\"index\" ><img src=\"/resources/css/img/logout.png\" alt=\"\" style=\"width: 10%;\"></a>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/JUS/view.jsp(29,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <div >\r\n");
          out.write("				<a href=\"login\" style=\"margin: 10px;\">로그인</a>\r\n");
          out.write("                <a href=\"join\">회원가입</a>   \r\n");
          out.write("             	</div>\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  	");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                  	");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                  	");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/JUS/view.jsp(51,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_limit !=board.request_order}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  		");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                 		");
          if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write(" \r\n");
          out.write("                  	");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /WEB-INF/views/JUS/view.jsp(52,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reqOK == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("                    		<a class=\"btn\" id=\"request\" data-value=\"0\" style=\"background-color: blue; color: white;\">신청하기</a>\r\n");
          out.write("                 		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /WEB-INF/views/JUS/view.jsp(55,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reqOK != 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("                  			<a class=\"btn\" id=\"request\" style=\"background-color: red; color: white;\" data-value=\"1\">신청취소</a>\r\n");
          out.write("                  		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/JUS/view.jsp(59,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reqOK != 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  			<a class=\"btn\" id=\"request\" style=\"background-color: red; color: white;\" data-value=\"1\">신청취소</a>\r\n");
          out.write("                  	");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                  		<h2>마감입니다</h2>\r\n");
          out.write("                  	");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /WEB-INF/views/JUS/view.jsp(67,18) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${recooOK == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("                     <!-- 추천안했을떄 -->\r\n");
          out.write("                    <button class=\"w3-button w3-black w3-round\" id=\"recommend\" style=\"margin: 10px;\">\r\n");
          out.write("                    	<img src=\"/resources/css/img/heartO.png\" alt=\"\" style=\"width:50px; height:50px\">\r\n");
          out.write("						&nbsp;<span class=\"recommend_count\"> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_recommend}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("					</button> \r\n");
          out.write("                   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /WEB-INF/views/JUS/view.jsp(75,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${recooOK != 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" \r\n");
          out.write("                     <!-- 추천 했을때 -->\r\n");
          out.write("                    <button class=\"w3-button w3-black w3-round\" id=\"recommend\" style=\"margin: 10px;\">\r\n");
          out.write("                    	<img src=\"/resources/css/img/heartsX.png\" alt=\"\" style=\"width:50px; height:50px\">\r\n");
          out.write("						&nbsp;<span class=\"recommend_count\"> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_recommend}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("					</button> \r\n");
          out.write("					\r\n");
          out.write("                   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /WEB-INF/views/JUS/view.jsp(83,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.user_name == board.user_name}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("  \r\n");
          out.write("                    	<a class=\"btn\" href=\"delete?board_idx=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_idx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"writingdel\" style=\"background-color: blue; color: white;\">글 삭제</a>\r\n");
          out.write("                    	<a class=\"btn\" href=\"modify?board_idx=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.board_idx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"writingmod\" style=\"background-color: blue; color: white;\">글 수정</a>\r\n");
          out.write("                  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }
}
